import { h as head, e as escape_html, c as pop, p as push } from "../../../chunks/index.js";
import "../../../chunks/client.js";
import { a as answerHandler } from "../../../chunks/AnswerHandler.js";
function _page($$payload, $$props) {
  push();
  head($$payload, ($$payload2) => {
    $$payload2.title = `<title>AI Ready! - Sedna AI Gameshow</title>`;
  });
  $$payload.out += `<div class="sedna-section-bg min-h-screen"><div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16 lg:py-20"><div class="text-center"><div class="text-8xl mb-6 animate-bounce-slow">🎉</div> <h1 class="text-5xl md:text-7xl font-retro-bold text-sedna-bright-yellow mb-8 bg-sedna-dark-slate-blue px-8 py-4 rounded-lg shadow-lg">YOU'RE AI READY!</h1> <div class="sedna-card mb-8"><h2 class="text-3xl font-retro-bold text-sedna-dark-slate-blue mb-4">🏆 Congratulations, ${escape_html("Champion")}!</h2> <p class="sedna-text text-xl mb-6">You've successfully completed the Sedna AI Gameshow and demonstrated your understanding of AI in government and public sector applications!</p> <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6"><div class="bg-sedna-light-grey border-2 border-sedna-cool-blue rounded-lg p-6"><div class="text-2xl font-retro-bold text-sedna-cool-blue mb-2">🏆 Final Score</div> <div class="text-4xl font-retro-bold text-sedna-dark-slate-blue">${escape_html(answerHandler.getScore())}</div></div> <div class="bg-sedna-light-grey border-2 border-sedna-orange rounded-lg p-6"><div class="text-2xl font-retro-bold text-sedna-orange mb-2">🎯 Accuracy</div> <div class="text-4xl font-retro-bold text-sedna-dark-slate-blue">${escape_html(answerHandler.getAccuracy())}%</div></div> <div class="bg-sedna-light-grey border-2 border-sedna-bright-yellow rounded-lg p-6"><div class="text-2xl font-retro-bold text-sedna-bright-yellow mb-2">📊 Questions</div> <div class="text-4xl font-retro-bold text-sedna-dark-slate-blue">${escape_html(0)}</div></div></div> <div class="bg-sedna-light-grey border-2 border-sedna-muted-gold rounded-lg p-6"><h3 class="text-2xl font-retro-bold text-sedna-muted-gold mb-3">🌟 Your Performance Level: ${escape_html(answerHandler.getDifficultyLevel())}</h3> <p class="sedna-text">${escape_html(answerHandler.getEncouragement())}</p></div></div> <div class="sedna-card border-2 border-sedna-bright-yellow bg-gradient-to-r from-sedna-bright-yellow to-sedna-muted-gold mb-8"><div class="text-6xl mb-4">🎁</div> <h2 class="text-3xl md:text-4xl font-retro-bold text-white mb-4">You’re entered into the AirPod Raffle! Spin the wheel for a chance at bonus entries!</h2> <p class="text-white text-xl font-sedna-bold text-center">You've earned it! Head to the Sedna booth to claim your rewards.</p></div> <div class="flex justify-center"><button class="sedna-btn sedna-btn-accent text-2xl py-6 px-12">🔄 PLAY AGAIN</button></div> <div class="mt-12"><p class="sedna-text text-sedna-steel-blue-tint">Powered by <span class="sedna-highlight">Sedna Consulting Group</span></p></div></div></div></div>`;
  pop();
}
export {
  _page as default
};
